---
abstract: 'immutablize C::A::F object'
author: ~
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-Fast-Immutablize
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
